# Generated by Django 2.2.6 on 2019-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='unbuy_string',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
