# Generated by Django 3.0.9 on 2020-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wish_santa_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='santa_nick',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
