# Generated by Django 3.2.9 on 2021-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20200817_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
